#!/usr/bin/env python

"""
Author: Kirschen Seah
Copyright © 2017 Kirschen Seah. All Rights Reserved
Released under the MIT License
"""


import argparse

from pushover_complete import PushoverAPI
from PushoverConfig import PushoverConfig


pc = PushoverConfig()
pc.read()

parser = argparse.ArgumentParser(description='Send a pushover message')
parser.add_argument('-u', '--user', dest='user_key', default=pc.user_key, help='Pushover user key')
parser.add_argument('-a', '--app', dest='app_key', default=pc.app_key, help='Pushover app key')
parser.add_argument('-t', '--title', help='Title for alert')
parser.add_argument('message', help='Pushover messsage')

args = parser.parse_args()

papi = PushoverAPI(args.app_key)
papi.send_message(args.user_key, args.message, title=args.title)
